filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /var/log/python-test.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

fields:
  blog_name: sysadmins
  service_type: webserver
  cloud_provider: aws

setup.kibana:
  host: "127.0.0.1:5601"
  username: "elastic"
  password: "changeme"

output.elasticsearch:
  hosts: ["https://127.0.0.1:9200"]
  # protocol: "http"
  username: "elastic"
  password: "PASSWORD"